-- MySQL Script generated by MySQL Workbench
-- Tue Jul 27 18:11:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`couple`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`couple` ;

CREATE TABLE IF NOT EXISTS `mydb`.`couple` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `meet_at` DATE NOT NULL,
  `together_at` DATE NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `gender` TINYINT(1) NOT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `invite_code` VARCHAR(45) NOT NULL,
  `is_enable` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Couple_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Mate_Couple_idx` (`Couple_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mate_Couple`
    FOREIGN KEY (`Couple_id`)
    REFERENCES `mydb`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`calender` ;

CREATE TABLE IF NOT EXISTS `mydb`.`calender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_date` DATE NOT NULL,
  `year` SMALLINT(4) NOT NULL,
  `month` TINYINT(2) NOT NULL,
  `day` TINYINT(2) NOT NULL,
  `day_of_week` TINYINT(2) NOT NULL,
  `is_holiday` TINYINT(1) NOT NULL,
  `holiday_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`anniversary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`anniversary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`anniversary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_date` DATE NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `couple_id` INT NOT NULL,
  `calender_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_anniversary_couple1_idx` (`couple_id` ASC) VISIBLE,
  INDEX `fk_anniversary_calender1_idx` (`calender_id` ASC) VISIBLE,
  CONSTRAINT `fk_anniversary_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `mydb`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anniversary_calender1`
    FOREIGN KEY (`calender_id`)
    REFERENCES `mydb`.`calender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`diary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`diary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `mood_score` SMALLINT(3) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  `calender_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diary_mate1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_diary_calender1_idx` (`calender_id` ASC) VISIBLE,
  CONSTRAINT `fk_diary_mate1`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diary_calender1`
    FOREIGN KEY (`calender_id`)
    REFERENCES `mydb`.`calender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`note` ;

CREATE TABLE IF NOT EXISTS `mydb`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_by` INT NOT NULL,
  `modified_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_note_mate1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_note_mate2_idx` (`modified_by` ASC) VISIBLE,
  CONSTRAINT `fk_note_mate1`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_mate2`
    FOREIGN KEY (`modified_by`)
    REFERENCES `mydb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visited_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`visited_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`visited_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_by` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_visited_type_couple1_idx` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_visited_type_couple1`
    FOREIGN KEY (`created_by`)
    REFERENCES `mydb`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`to_do_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`to_do_list` ;

CREATE TABLE IF NOT EXISTS `mydb`.`to_do_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_completed` TINYINT(1) NOT NULL,
  `visited_type_id` INT NOT NULL,
  `couple_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_to_do_list_visited_type1_idx` (`visited_type_id` ASC) VISIBLE,
  INDEX `fk_to_do_list_couple1_idx` (`couple_id` ASC) VISIBLE,
  CONSTRAINT `fk_to_do_list_visited_type1`
    FOREIGN KEY (`visited_type_id`)
    REFERENCES `mydb`.`visited_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_to_do_list_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `mydb`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visited_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`visited_place` ;

CREATE TABLE IF NOT EXISTS `mydb`.`visited_place` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `visited_type_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `first_visited_date` DATE NOT NULL,
  `last_visited_date` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `couple_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visited_place_visited_type1_idx` (`visited_type_id` ASC) VISIBLE,
  INDEX `fk_visited_place_city1_idx` (`city_id` ASC) VISIBLE,
  INDEX `fk_visited_place_couple1_idx` (`couple_id` ASC) VISIBLE,
  CONSTRAINT `fk_visited_place_visited_type1`
    FOREIGN KEY (`visited_type_id`)
    REFERENCES `mydb`.`visited_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visited_place_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visited_place_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `mydb`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visited_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`visited_record` ;

CREATE TABLE IF NOT EXISTS `mydb`.`visited_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `visited_place_id` INT NOT NULL,
  `couple_id` INT NOT NULL,
  `visited_date` DATE NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rate` TINYINT(2) NOT NULL,
  `would_want_to_return_visit` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_visited_record_visited_place1_idx` (`visited_place_id` ASC) VISIBLE,
  INDEX `fk_visited_record_couple1_idx` (`couple_id` ASC) VISIBLE,
  CONSTRAINT `fk_visited_record_visited_place1`
    FOREIGN KEY (`visited_place_id`)
    REFERENCES `mydb`.`visited_place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visited_record_couple1`
    FOREIGN KEY (`couple_id`)
    REFERENCES `mydb`.`couple` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
